nama = input("Nama                  : ")
nim = int(input("NIM                   : "))
kelasP = int(input("Kelas Paralel         : "))
ttl = input("Tempat/Tanggal Lahir  : ")
alamat = input("Alamat                : ")
hobby = input("Hobby                 : ")
nomor = int(input("No. HP                : "))

print("\nNama                  :", nama)
print("NIM                   :", nim)
print("Kelas Paralel         :", kelasP)
print("TTL                   :", ttl)
print("Alamat                :", alamat)
print("Hobby                 :", hobby)
print("No. HP                :", nomor)